name: Integration

on: push

jobs:
  int:
    name: 'Test & Runtime & Thesis'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v14-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v14-
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Run runtime measurement
        run: npm run runtime
      - name: Generate runtime measurement table
        run: npm run ctt
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: thesis
          root_file: thesis_en.tex
          latexmk_shell_escape: true
      - name: Upload the compiled pdf & csv
        uses: actions/upload-artifact@v2.2.4
        with:
          name: thesis
          path: |
            thesis/thesis_en.pdf
            gen/*.csv
          if-no-files-found: error