name: Integration

on: push

jobs:
  test:
    name: 'Run tests & runtime measurement'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v14-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v14-
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Run runtime measurement
        run: npm run runtime
      - uses: actions/upload-artifact@v3
        with:
          path: measurement.csv
  build_latex:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Git repository
          uses: actions/checkout@v2
          name: Compile LaTeX document
          uses: xu-cheng/latex-action@v2
          with:
            root_file: |
              thesis/thesis_en.tex
            latexmk_shell_escape: true
        - name: Upload the compiled pdf
          uses: actions/upload-artifact@v2.2.4
          with:
            name: thesis
            path: |
              thesis/thesis_en.pdf
            if-no-files-found: error