name: Tests

on: [pull_request]

jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v14-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v14-
      - name: Install Dependencies
        run: npm install
      - name: Run All Node.js Tests
        run: npm run test
